export const BADGES_CONFIG = [
  { key: 'egg_free', label: 'Egg Free' },
  { key: 'sustainable', label: 'Sustainable' },
  { key: 'peanut_free', label: 'Peanut Free' },
  { key: 'primal', label: 'Primal' },
  { key: 'sulfite_free', label: 'Sulfite Free' },
  { key: 'nut_free', label: 'Nut Free' },
  { key: 'vegan', label: 'Vegan' },
  { key: 'no_preservatives', label: 'No Preservatives' },
  { key: 'soy_free', label: 'Soy Free' },
  { key: 'msg_free', label: 'MSG Free' },
  { key: 'no_artificial_colors', label: 'No Artificial Colors' },
  { key: 'sugar_free', label: 'Sugar Free' },
  { key: 'no_artificial_flavors', label: 'No Artificial Flavors' },
  { key: 'vegetarian', label: 'Vegetarian' },
  { key: 'no_artificial_ingredients', label: 'No Artificial Ingredients' },
  { key: 'no_additives', label: 'No Additives' },
  { key: 'corn_free', label: 'Corn Free' },
  { key: 'dairy_free', label: 'Dairy Free' },
  { key: 'paleo', label: 'Paleo' },
  { key: 'gluten_free', label: 'Gluten Free' },
];
