export const CUISINES = [
  { key: '1', value: 'African' },
  { key: '2', value: 'Asian' },
  { key: '3', value: 'American' },
  { key: '4', value: 'British' },
  { key: '5', value: 'Cajun' },
  { key: '6', value: 'Caribbean' },
  { key: '7', value: 'Chinese' },
  { key: '8', value: 'Eastern European' },
  { key: '9', value: 'European' },
  { key: '10', value: 'French' },
  { key: '11', value: 'German' },
  { key: '12', value: 'Greek' },
  { key: '13', value: 'Indian' },
  { key: '14', value: 'Irish' },
  { key: '15', value: 'Italian' },
  { key: '16', value: 'Japanese' },
  { key: '17', value: 'Jewish' },
  { key: '18', value: 'Korean' },
  { key: '19', value: 'Latin American' },
  { key: '20', value: 'Mediterranean' },
  { key: '21', value: 'Mexican' },
  { key: '22', value: 'Middle Eastern' },
  { key: '23', value: 'Nordic' },
  { key: '24', value: 'Southern' },
  { key: '25', value: 'Spanish' },
  { key: '26', value: 'Thai' },
  { key: '27', value: 'Vietnamese' },
];
