export const TYPES = [
  { key: '1', value: 'main course' },
  { key: '2', value: 'side dish' },
  { key: '3', value: 'dessert' },
  { key: '4', value: 'appetizer' },
  { key: '5', value: 'salad' },
  { key: '6', value: 'bread' },
  { key: '7', value: 'breakfast' },
  { key: '8', value: 'soup' },
  { key: '9', value: 'beverage' },
  { key: '10', value: 'sauce' },
  { key: '11', value: 'marinade' },
  { key: '12', value: 'fingerfood' },
  { key: '13', value: 'snack' },
  { key: '14', value: 'drink' },
];
